### ISSUE TITLE
ACE2 not DE - compositional effect

### ISSUE THREAD

**Issue by ChristophH** [pachterlab/BP_2020_2#2] opened 2021-03-17 21:33 UTC
Hi Sina and Lior,

First, I absolutely agree with your main points  about problems with log1p (which is why I've developed the sctransform R package) and detection rate as a useful proxy for expression level (assuming negligible sequencing depth differences).

However, I don't think the statement "it is clear that ACE2 has significantly lower mRNA expression in the lungs of aged mice than young mice" is accurate given the data. When clustering the cells, and looking at ACE2 expression (or detection) per cluster across the two age groups, I don't see significant differences. But there is a significant difference in which age group contributes to the ACE2-expressing clusters. For example 74% of the cells for the main ACE2 cluster (AT2 cells I guess) come from age 3 samples, when overall only 55% of the cells come from that age group. Overall there is an enrichment for the age 3 group in the top 7 clusters when ranked by ACE2 detection rate.

So the differences presented in Fig1b could be explained by these compositional differences, and perhaps a more accurate statement would be that 'young mice have significantly more cells of type x, y and z'.

Edit: I just noticed [Zhang et al.](https://www.frontiersin.org/articles/10.3389/fgene.2020.00942/full) actually address the same point

> We also noticed another preprint manuscript (Booeshaghi and Pachter, 2020) which drew a seemingly different conclusion from our analysis in the expression of gene ACE2. However, certain differences do exist in the analysis from the two groups. First, the major conclusion in our study only focuses on the Ace2 expression within three cell types, which do not consider any other cell types in the data, while the other manuscript evaluated the proportion of Ace2-expressing cells in all cell types and found that younger mice had a higher overall proportion. Second, the reason we chose the presented “within-cell-type” comparison is that the proportion of each cell type is likely to alter between different groups (age groups in this case) and would affect the assessment of gene expression level.

Any comments or clarifications from your side?

Cheers,
Christoph

PS: [my analysis notebook ](https://github.com/pachterlab/BP_2020_2/files/6159832/Pachter_BP_2020_2.pdf)

**Comment by lakigigar** [comment] 2021-03-18 01:14
Hi Cristoph, 

Thanks for examining this. Indeed, we considered this possibility, but in an examination segregated by cell type we still found decrease *in ciliated cells*, i.e. decrease in ciliated cells positive for ACE2 relative to the number of ciliated cells. See Fig 1c of a preprint we wrote specifically on this matter: [https://www.biorxiv.org/content/10.1101/2020.04.02.021451v1](https://www.biorxiv.org/content/10.1101/2020.04.02.021451v1). I think the reason for the discrepancy may be the clustering. We went to considerable lengths to cluster in a way where labels transferred well with the annotations from Angelidis et al. and Traveaglini et al. In fact, the way we annotated the clusters for Fig 2c was by finding (DE) marker genes and then cross-referencing them to those papers (see https://github.com/pachterlab/BP_2020/blob/master/notebooks/celltype.ipynb).

Of course this is tricky to do and it's possible deeper analysis with more data could shed more light on this. Interestingly others have confirmed our claim, see e.g. [https://www.nature.com/articles/s41467-020-19145-6](https://www.nature.com/articles/s41467-020-19145-6) (visible decrease in ciliated cells although not statistically significant) and also [https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(20)30352-2/fulltext](https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(20)30352-2/fulltext) which states "Interestingly, we observed increased ACE2 in young children and control group bronchioles, suggesting a possible protective effect by ACE2 expression."

The reanalysis by Zhang of Angelidis et al. also annotated cell types (although with fewer clusters) but I think they looked at "expression level" rather than percent cells expression ACE2, which goes back to the point we made that this is problematic. 

BTW, Bilinka et al. looked at olfactory epithelium, olfactory bulb, and frontal cortex, and also saw decreased ACE2 expression with age. Of course it's not lung but would be interesting to investigate further as well.
 [https://pubs.acs.org/doi/pdf/10.1021/acschemneuro.0c00210](https://pubs.acs.org/doi/pdf/10.1021/acschemneuro.0c00210)

**Comment by ChristophH** [comment] 2021-03-18 09:23
Thank you for your prompt reply. I had not seen the other preprint - there it is a different story.
In the end it might come down to establishing consistent cell type annotations / guided clustering methods to do this in a robust way.

Hopefully [Muus, Luecken et al. (Single-cell meta-analysis of SARS-CoV-2 entry genes across tissues and demographics)](https://www.nature.com/articles/s41591-020-01227-z) have done this. I have not looked at their methods in detail, but it is an impressive sample size with 37,530 cells from 157 donors for multiciliated cells, and 155,512 cells from 104 donors for AT2 cells (among many more cell types). They find an increase in ACE2 expression with age in AT2 and multiciliated cells. In the discussion they actually comment on this preprint:

> Our findings in human and mouse models are consistent with respect to smoking and age associations. In line with our human data, we find an increase in Ace2 expression in maturing mice (2–4 months). Others have reported lower expression of entry factors in aged mice (24 months), showing potential limitations of mice as a model system.

**Comment by lakigigar** [comment] 2021-03-18 22:39
The Muus, Luecken et al. paper performs a very comprehensive analysis, but ACE2 expression is calculated as log_2(TPM+1), which is one reason we wrote the log1p paper. I therefore suspect that the issue is not about mouse having limits as a model system, but rather log1p having limits as a normalization method. Having said that, you're right that it's an impressive dataset, and in fact we have been taking a close look at it in my group.

**Closed as completed** 2021-03-26 14:43 UTC
